// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiTtnUCZcIIC_PXMI34WVnbDeECxEOt0',
    appId: '1:411151969879:android:5ab2625923aa3738f1fd12',
    messagingSenderId: '411151969879',
    projectId: 'kp-absen',
    storageBucket: 'kp-absen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSrNx6_zg0jGq5ir4JmiEAd0yPMpF36c8',
    appId: '1:411151969879:ios:5560c1ac160c4e60f1fd12',
    messagingSenderId: '411151969879',
    projectId: 'kp-absen',
    storageBucket: 'kp-absen.appspot.com',
    iosClientId: '411151969879-3bdmgbqtdslfd8od8toitursgdjvk5j9.apps.googleusercontent.com',
    iosBundleId: 'xmirz.com.kpMobile',
  );
}
